version: '3'
services:
  app:
    container_name: lk-app
    build: .
    ports:
      - 80:80
    restart: always
    volumes:
      - api:/usr/src/lk-app/
    networks:
      - network_service
volumes:
  api:

networks:
  network_service:
    driver: bridge
