name: lk-app

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Restart app
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd /root/Dev/card-balance
          git pull
          docker-compose up --build -d
        host: ${{ secrets.REMOTE_HOST }}
        user: root
        pass: ${{ secrets.SERVER_ROOT_PASSWORD}}
        args: "-tt"
