name: lk-app

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Restart app
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd ~/Dev/card-balance && git pull
          docker build . -t lk-app
          docker run -d -p 80:80 lk-app
        host: ${{ secrets.REMOTE_HOST }}
        user: root
        pass: ${{ secrets.SERVER_ROOT_PASSWORD}}
